name: car_sales_dbt
version: "1.0.0"
config-version: 2

profile: car_sales_dbt

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  car_sales_dbt:
    staging:
      +materialized: view
      +schema: STAGING
    marts:
      +materialized: table
      +schema: MART
